# Define o interpretador Python
PYTHON = python3

# Regra padrão: roda o script main.py
all: run

# Regra para executar o script Python
run:
	$(PYTHON) main.py

# Regra para limpar (opcional, mas boa prática)
# remove arquivos temporários ou gerados
clean:
	@echo "Nenhuma limpeza específica necessária para este projeto."

.PHONY: all run clean